const NEW_TODO = 'NEW_TODO';

const EDIT_TODO = 'EDIT_TODO';

const TOGGLE_TODO = 'TOGGLE_TODO';

const DELETE_TODO = 'DELETE_TODO';

const FILTER_TODOS = 'FILTER_TODOS';

export default {
  NEW_TODO,
  EDIT_TODO,
  TOGGLE_TODO,
  DELETE_TODO,
  FILTER_TODOS
}
